### ISSUE TITLE
Implement NFA -> DFA translation

### ISSUE THREAD

**Issue by kddnewton** [kddnewton/regular_expression#37]
At the moment our state machines are non-deterministic, meaning they can transition to multiple states for a given [state,character] pair. In practice this means we have to implement recursive backtracking when we convert into bytecode. 

An optimization that will make this a lot better is to first convert to a DFA by walking the NFA and simulating all possible inputs. We'll need to maintain this as a separate implementation, as some things like backreferences won't work/won't be easily implementable. But if we scan the pattern first, we should be able to tell if we can use this implementation.

**Comment by tomstuart** [comment]
Kevin pushed up some work-in-progress on the `dfa` branch; I’m taking a look at it now to see if I can get it fully working.

**Comment by tomstuart** [comment]
Debugging this: [`next if result.key?(states)`](https://github.com/kddnewton/regular_expression/commit/1448cd61e99e1be2834823d0fdacd53dc17409ba#diff-b6be4eea1d48bc49be08c12fbeceecb075e08c929c859ecf04bf1e85f03f52d1R27) is not right, because the whole idea is that we’re [adding new sets of NFA states to `result`](https://github.com/kddnewton/regular_expression/commit/1448cd61e99e1be2834823d0fdacd53dc17409ba#diff-b6be4eea1d48bc49be08c12fbeceecb075e08c929c859ecf04bf1e85f03f52d1R57-R58) before we [push them onto the worklist](https://github.com/kddnewton/regular_expression/commit/1448cd61e99e1be2834823d0fdacd53dc17409ba#diff-b6be4eea1d48bc49be08c12fbeceecb075e08c929c859ecf04bf1e85f03f52d1R62).

I’ve pushed some commits which change the logic: rather than trying to skip worklist entries, we only add new sets of NFA states to the worklist if they aren’t already in `results`. This way we’re relying entirely on the worklist to tell us what work remains, and allowing `results` to accumulate the mappings between NFA states and DFA states as we go.

Example output for `./bin/parse 'ab?c*de':

![nfa](https://user-images.githubusercontent.com/3192/126363200-d21d2aa7-bee6-497e-9e64-8b55fef6dc88.png)

![dfa](https://user-images.githubusercontent.com/3192/126363217-2a4561b9-ff6c-4945-9b8b-f7ee1a193a4a.png)

I haven’t convinced myself that this is entirely correct yet, but it’s progress of a sort!

**Comment by tomstuart** [comment]
Rebased the `dfa` branch to include the label changes from #44.

**Comment by tomstuart** [comment]
I experimented with converting the problematic `a?a?a?aaa` regular expression from #47 to see what happened — ideally we should be able to match this expression successfully after DFA conversion because no backtracking will be needed.

Here’s the NFA:

![nfa](https://user-images.githubusercontent.com/3192/126462371-a9acdc51-724b-4067-9213-be32557c91ab.png)

Here’s the resulting DFA:

![dfa](https://user-images.githubusercontent.com/3192/126462398-b040941d-943c-4925-a85d-cbd9273b83fb.png)

So there are a few obvious problems to fix:

* The start state isn’t a start state
* The finish states aren’t finish states
* There are duplicate transitions

I’ll address these now.

**Comment by noahgibbs** [comment]
TBF it's a problematic regexp. I was testing it because the NFA-to-DFA paper specifically use it as an example of a regexp that most normal implementations screw up badly on :-)

**Comment by tomstuart** [comment]
Okay, having fixed those problems, the DFA now looks like this:

![dfa](https://user-images.githubusercontent.com/3192/126475518-10756384-779e-4f63-98b0-5dfff31b3103.png)

And, as expected, that matches the correct strings:

```
>> require 'regular_expression'
=> true
>> ast = RegularExpression::Parser.new.parse('a?a?a?aaa')
=> #<RegularExpression::AST::Root:0x00007fc65d147eb0 @expressions=[#<Regula...
>> nfa = ast.to_nfa
=> #<RegularExpression::NFA::StartState:0x00007fc65d8ddb48 @label="Start", ...
>> dfa = RegularExpression::DFA.build(nfa)
=> #<RegularExpression::NFA::StartState:0x00007fc65992c170 @label="Start,1,...
>> bytecode = RegularExpression::Bytecode.compile(dfa)
=> #<RegularExpression::Bytecode::Compiled:0x00007fc659a507e0 @insns=[#<str...
>> 0.upto(10).map { |n| 'a' * n }.select { |string| RegularExpression::Interpreter.new(bytecode).match?(string) }
=> ["aaa", "aaaa", "aaaaa", "aaaaaa", "aaaaaaa", "aaaaaaaa", "aaaaaaaaa", "aaaaaaaaaa"]
```

The problem now is that I’ve completely hacked the notion of “deduplicating” the transitions, by relying on comparing two transitions with `Transition#matches?`. This works here but won’t work in general because e.g. a `Transition::Value` and `Transition::Any` will “match” but they’re not actually duplicates — if we throw the wrong one away then we’ll end up with an incorrect DFA. So it needs more thought to figure out what deduplication of transitions should look like in general. (In a theoretical setting we only have value & epsilon transitions so this problem doesn’t exist, but we have all kinds of other transitions to make our NFA representation more compact.)

**Comment by tomstuart** [comment]
I found myself getting lost, so I did some [renaming](https://github.com/kddnewton/regular_expression/compare/c907745..bc7be6d) to clarify what’s going on.

**Comment by tomstuart** [comment]
Cleanup aside, I’m currently working on making the DFA conversion work correctly for this NFA of the regular expression `[a-d]g|[c-f]h`:

![nfa](https://user-images.githubusercontent.com/3192/126633913-58fd160e-c2c1-40dd-994a-d7abeb6e9333.png)

This is tricky because the two ranges `[a-d]` and `[c-f]` overlap, so the resulting DFA should look like this:

![dfa](https://user-images.githubusercontent.com/3192/126634025-45ab14ec-28d9-4e9f-81fb-c842dda178a3.png)

Namely: for the automaton to be deterministic, reading `c` or `d` must put us into a distinct state where we can read either `g` or `h` to reach the finish state, whereas reading `a` or `b` forces us to read `g` (and likewise for `e` or `f` forcing `h`).

To make this work we need to be able to a) spot that the `[a-d]` and `[c-f]` ranges overlap, and b) split them into disjoint pieces (`[a-b]`, `[c-d]` and `[e-f]`) to use when constructing the DFA transitions. (I have a bad feeling about POSIX bracket expressions (`[[:alnum:]]` and friends) but I’m focusing on this simpler case for now.)

**Comment by tomstuart** [comment]
Kevin suggested just merging what currently works (i.e. `Transition::Value` and `Transition::Epsilon` only), which is a good idea, so I’m putting together a PR for that now.

**Comment by tomstuart** [comment]
#101 is the PR for the work so far.
