### ISSUE TITLE
Bug: deeper backtracking still doesn't seem to work

### ISSUE THREAD

**Issue by noahgibbs** [kddnewton/regular_expression#97]
10 optional a's followed by ten mandatory a's? Still doesn't match 15 a's.

~~~
noah@Noahs-MacBook-Pro-3 regular_expression % irb
irb(main):001:0> require_relative "lib/regular_expression"
=> true
irb(main):002:0> p = RegularExpression::Pattern.new("a?" * 10 + "a" * 10)
=> #<RegularExpression::Pattern:0x00007f92710702f0 @bytecode=#<RegularExpression::Bytecode::Compiled:0x00007f92908e71d0 @insns=[#<struct RegularExpression::Bytecode::Insns::Start...
irb(main):003:0> p.match?("a" * 15)
=> nil
~~~

The Ruby builtin regexps do this fine:

~~~
irb(main):006:0> re = Regexp.new("a?" * 10 + "a" * 10)
=> /a?a?a?a?a?a?a?a?a?a?aaaaaaaaaa/
irb(main):007:0> re.match?("a" * 15)
=> true
~~~

**Comment by noahgibbs** [comment]
Tested via head-of-master, commit b94d679f4dad9e4b2433164b824cf48b5c908c31

**Comment by noahgibbs** [comment]
Not surprisingly, also fails when invoked with number of occurrences rather than building a huge regexp.

That is, "(a?){10}a{10}" behaves identically.

**Comment by Maaarcocr** [comment]
during the weekend I dig around this, and the simplest failing case is `a?a` does not match `a`. I think this is due to this line of code: https://github.com/kddnewton/regular_expression/blob/3cce64d6d0988c67650767ad900bc72c12fa8476/lib/regular_expression/bytecode.rb#L21

When we visit a state that we had already visited we skip. This works fine in most cases, except when we visit one state twice but the fallback is different. 

Take for example this nfa: 
![nfa](https://screenshot.click/26-14-plb8v-yhnf2.png)

We would visit state `2` twice, once when we come from `a` and once when we come from the epsilon transition. The epsilon transition has as its fallback the failure state, because we its the second and last transition out of state `1`.

Due to this, we never add a fallback instruction that lets us fail back to state number one after we consumed an `a`, as seen in this cfg: 

![cfg](https://screenshot.click/26-17-nnwgd-3lmo0.png)

**Comment by Maaarcocr** [comment]
one way to fix this would be to: 

1) record from which state we entered the current state
2) have some sort of fallback jumptable indexed by the previous state

With this we could have different fallbacks for each state and also produce sensible assembly I think.
